### ISSUE TITLE
convert_conv_following_space_to_depth_to_dcr in QuickSRNet

### ISSUE THREAD

**Issue by Rm1n90** [quic/aimet-model-zoo#32]
Hi @quic-bharathr, I wanted to retrain QuickSRNet on my own dataset but realized the code for `convert_conv_following_space_to_depth_to_dcr` is not available in the repo. Would you please provide the code?

Thanks!!

**Comment by zhgqcn** [comment]
> Hi @quic-bharathr, I wanted to retrain QuickSRNet on my own dataset but realized the code for `convert_conv_following_space_to_depth_to_dcr` is not available in the repo. Would you please provide the code?
> 
> Thanks!!

请问解决了吗
