### ISSUE TITLE
Where is the code for Mobilebert use QAT?

### ISSUE THREAD

**Issue by wminiboy** [quic/aimet-model-zoo#40]
Where is the code for Mobilebert use QAT ? I can't find .

**Comment by quic-mangal** [comment]
@quic-hanwxion Could you please help answer this. Thanks.

**Comment by quic-hanwxion** [comment]
Hi @wminiboy , we decided to publish only evaluation pipeline and not the QAT pipeline. If you want to try it on your self, you can follow the AIMET QAT instructions on this page: https://quic.github.io/aimet-pages/releases/latest/api_docs/torch_quantsim.html#code-example-quantization-aware-training-qat:~:text=learned%20during%20training.-,Code%20Example%20%2D%20Quantization%20Aware%20Training%20(QAT),-%C2%B6

**Comment by wminiboy** [comment]
@quic-hanwxion If it will be released in the future, can you send me the development version now? For learning reference . Thank you    
Email:wminiboy@gmail.com

**Comment by quic-hanwxion** [comment]
Hi @wminiboy , the AIMET version being used in MobileBert is indicated here: https://github.com/quic/aimet-model-zoo/blob/develop/aimet_zoo_torch/mobilebert/MobileBert.md#:~:text=tested%20using%20AIMET%20version%201.27.0%20(i.e.%20set%20release_tag%3D%221.27.0.

By "development version" do you mean the actual QAT script? If so, it's not meant for external release and thus can't be sent. Sorry about that!

**Comment by wminiboy** [comment]
OK， Thank you.
